GET http://localhost:3100/fols/search
?keyword=
&car=
Content-Type: application/json

###
POST http://ec2-54-165-210-52.compute-1.amazonaws.com:3100/fols/
Content-Type: application/json

{
  "car": "Mercedes"
}

###

POST http://172.31.21.70:3100/signup/
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "guilherme@email.com",
  "password": "1234test",
  "equipment": ["BMW", "Ferrari"]
}

###

POST http://localhost:3100/user/login
Content-Type: application/json

{
  "login": "koliveira",
  "password": "429260"
}

###

POST http://localhost:3100/user/remove
Content-Type: application/json

{
  "chave": "62816586e4c4bfbc24d56069"
}